### ISSUE TITLE
没有settings文件

### ISSUE THREAD

**Issue by puzi12138** [SatoSouta/Typecho-plugin-APlayerAtBottom#10]
f12显示file_get_contents(/www/wwwroot/www.XXX.com/usr/plugins/APlayerAtBottom/settings.json): failed to open stream: No such file or directory in <b>/www/wwwroot/www.XXX.com/usr/plugins/APlayerAtBottom/Downplayer.php</b> on line <b>3</b><br />但我在源文件里并没有找到settings文件

**Comment by SatoSouta** [comment]
如果在插件源目录下没有生成settings.json的文件，请检查文件夹权限是否有给写入。
