### ISSUE TITLE
请添加qq音乐cookie导入

### ISSUE THREAD

**Issue by cfandora** [SatoSouta/Typecho-plugin-APlayerAtBottom#11]
qq音乐很多都需要vip，目前的api解析会直接跳过所有vip音乐

**Comment by SatoSouta** [comment]
会尽力在下个版本添加使用QQ音乐以及网易云音乐Cookie获取音乐内容

因为QQ音乐机制比较复杂，目前单独使用Meting无法解析，所以我采用的是Meto的公共API，因为拥有该要求，所以我们将会在近期尝试建立自己的QQ音乐API，您的要求我会尽力满足，请给我一点时间。

**Comment by SatoSouta** [comment]
目前暂时无法处理，Meting不支持QQ音乐Cookie

**Comment by cfandora** [comment]
感谢长时间的研究，辛苦了
